### ISSUE TITLE
Argument Cannot be Null

### ISSUE THREAD

**Issue by maximo1984** [maximo1984/Kingdom-Death-Maximo-Kijan-Mod#105]
I am getting this after hit location wound effects, and critical wound effects.  @KarateSnoopy let me know what the deal is if you can figure it out.  Its going to be a lot of work going through every hit location card and fixing whatever they broke.  I"m fine with putting in the work to move all the hit location scripts to an include folder organized by hierarchy.  Example, every single hit location has scripts on it. For a monster with 3 levels, then that same script is multiplied by 3.

I'd make a folder structure like this

hitLocations/

     wl/"each hit location card name"
     sa/"each hit location card name"

and so on for every monster.

**Comment by KarateSnoopy** [comment]
It looks like the .clone() in the scripts on the cards needs to pass in a table instead of position.
