### ISSUE TITLE
When loading mod for first time, clicking "Start showdown" first should tell user to load campaign first

### ISSUE THREAD

**Issue by KarateSnoopy** [maximo1984/Kingdom-Death-Maximo-Kijan-Mod#29]

**Comment by maximo1984** [comment]
You have to load a campaign first so the character sheets are loaded.

**Comment by KarateSnoopy** [comment]
Right.  This fix will let the users know if they click on "Start Showdown" when they haven't yet loaded a campaign that they need to.
