### ISSUE TITLE
Encourage error message

### ISSUE THREAD

**Issue by irishwizz** [maximo1984/Kingdom-Death-Maximo-Kijan-Mod#49]
I got the following error message when trying to encourage (and it did not remove one survival):

https://zupimages.net/up/18/27/vcm4.jpg

**Comment by KarateSnoopy** [comment]
Thanks.  I can reproduce this

**Comment by KarateSnoopy** [comment]
The same issue also happens if I click the "Knockdown" button next to "Encourage" likely the same bug
