### ISSUE TITLE
Camera problem?

### ISSUE THREAD

**Issue by irishwizz** [maximo1984/Kingdom-Death-Maximo-Kijan-Mod#83]
Hi,

I still have this camera issue: whenever the monster hits, the camera moves and gets very close to the board, so I have to reset the camera every time, see 
![image](https://user-images.githubusercontent.com/40929633/42493795-939b0616-841e-11e8-8a4e-0602b2fd07b9.png)

**Comment by KarateSnoopy** [comment]
Already fixed.  Dupe of https://github.com/maximo1984/Kingdom-Death-Maximo-Kijan-Mod/issues/4
