### ISSUE TITLE
Unable to attack now

### ISSUE THREAD

**Issue by LordLex** [maximo1984/Kingdom-Death-Maximo-Kijan-Mod#88]
Hmm, now I'm unable to get attacked.  here is the error 

Error in Script (Attack- 1daf26) function  <rollThedice>: chunk_1:(604,9- 11): attempt to call a nill vaule 

I'm assuming this is due to TTS new update but i am unsure.  This happens no matter the Showdown.

**Comment by LordLex** [comment]
Actually, the same is true when attacking.  Here is the error.

Error in Script (right roller_survAttack - ff240b) function <rollThedice> chunck_1:(561,9-11): attempt to call nil Vaule

I'm assuming this is also the case for the left roller.

**Comment by maximo1984** [comment]
Can you try to save/load and see if this fixes it. I may need some more information on what caused this. Circumstances of when it happened.

**Comment by LordLex** [comment]
Nevermind.  something must have changed on my end of on TTS's end since i posted this...it works now.  (i did go through a fresh save though so not sure what happened).
