### ISSUE TITLE
"Survivors are victorious" rule page on new game?

### ISSUE THREAD

**Issue by KarateSnoopy** [maximo1984/Kingdom-Death-Maximo-Kijan-Mod#9]
The rule page at called "Survivors are victorious" that's floating seems odd and its not clear why its there or what causes it to go away.

**Comment by maximo1984** [comment]
Added tag 'monster' to the description on this rule page. Anything with the tag 'monster' is destroyed when you click end showdown if they are in the main showdown and monster AI board zones.
