### ISSUE TITLE
Thrill Seeker disregarding the current Phase

### ISSUE THREAD

**Issue by n-Holmes** [maximo1984/Kingdom-Death-Maximo-Kijan-Mod#90]
The 'Thrill Seeker' fighting art currently adds an extra survival any time survival is added to a character. It should only be active during the showdown.

Edit: the following is actually the same issue as #89 
Tangentially, the 'Immortal' disorder currently prevents survival being removed manually for events which may cause it to be lost.

**Comment by maximo1984** [comment]
Good catch, I hadn't thought of losing survival when kijan and I worked on these scripts. I will think of something to fix it.

**Comment by maximo1984** [comment]
Fixed.
